### ISSUE TITLE
podrobná špecifikácia vonkajších interfejsov

### ISSUE THREAD

**Issue by AndrejNagy** [TIS2024-FMFI/serial-transformer#11]

**Comment by Nemeth03** [comment]
[Špecifikácia vonkajších interfejsov.docx](https://github.com/user-attachments/files/17545034/Specifikacia.vonkajsich.interfejsov.docx)

Rozpracovaná verzia.

**Comment by Nemeth03** [comment]
[Specifikacia.vonkajsich.interfejsov.docx](https://github.com/user-attachments/files/17784264/Specifikacia.vonkajsich.interfejsov.docx)

Treba dopísať komunikáciu s Autoguider kamerou.

**Comment by Nemeth03** [comment]
[Specifikacia.vonkajsich.interfejsov.docx](https://github.com/user-attachments/files/17799434/Specifikacia.vonkajsich.interfejsov.docx)
