### ISSUE TITLE
návrh používateľského rozhrania

### ISSUE THREAD

**Issue by AndrejNagy** [TIS2024-FMFI/serial-transformer#12]

**Comment by DjMaestr0** [comment]
![GUI-transformers](https://github.com/user-attachments/assets/15564475-b11d-4f48-ae59-3c25120d4f76)

verzia GUI pre transformacny modul pre teleskop

**Comment by DjMaestr0** [comment]
![GUI-hvezdaren](https://github.com/user-attachments/assets/4e100686-205c-4753-88df-d766a3276fa8)
Upravena verzia

**Comment by pavelpetrovic** [comment]
- ukazat logy smeruje na stranku so zoznamom suborov, ktore si pouzivatel moze downloadnut 
   (staci tuto vetu pridat pod obrazok do dokumentu Navrh)
- uvazujeme nad:  tlacidlo "downloadnuť všetky logy", "zmazať všetky logy" (ktore ale ma vyskakovaci potvrdzovacu stranku)
- zvazit ci sem nepridat aj konfiguraciu podla 3.2.5
- pridat dropdown, kde sa da vybrat casovy interval priemerovania tych dvoch zobrazenych rychlosti a dva textove labely, ktore ukazuju momentalnu hodnotu (posledny bod v grafe) vyjadrene ciselne (8.2.1)
- k editboxu Rychlost pridat tlacidlo "nastav" a este jeden read-only label zobrazujuci aktualnu platnu hodnotu (obe aj rucne nastavenu aj automaticku - ak sa momentalne vypocitava)
- pridat okienko pre univerzalny modul - staci jednoduche s tlacidlom "nacitat pravidla" a jednoducha statistika kolko paketov preslo a kolko z nich bolo modifikovanych

**Comment by DjMaestr0** [comment]
![modul pre hviezdaren](https://github.com/user-attachments/assets/c0cfac58-afe5-4423-bad4-2c17426b82b1)
![univerzalny modul](https://github.com/user-attachments/assets/11423328-3ae4-4f95-ae78-f9a6912ec6c2)

**Comment by pavelpetrovic** [comment]
zabudli sme na deaktivaciu prekladania - s tym vsetko sa preposiela, ale zastavit pakety netreba, takze to moze plnit ten ucel, ale malo by to byt aj v univerzalnom rezime a tiez deaktivaciu logovania - ci sa prechadzajuca komunikacia loguje alebo nie.

destruktivne akcie - ako napr. zmazanie logov - vzdy musia mat potvrdzovaci dialog.

**Comment by DjMaestr0** [comment]
![Image](https://github.com/user-attachments/assets/4fdf8d58-e787-4548-98c1-d948013f84c1)
![Image](https://github.com/user-attachments/assets/4357509a-5228-471d-8fea-48d0c1ee2426)
![Image](https://github.com/user-attachments/assets/4aab44c4-e25d-431a-b129-99191b54224c)

**Comment by DjMaestr0** [comment]
![Image](https://github.com/user-attachments/assets/bce14605-1758-47a5-b4f6-997ae06357a8)
![Image](https://github.com/user-attachments/assets/53c53a19-25fd-4f96-9fdc-e31b53f144d6)
aktualizovaná verzia modulu pre teleskop po upresnení zadávateľov
