### ISSUE TITLE
podrobný dátový model perzistentných údajov

### ISSUE THREAD

**Issue by AndrejNagy** [TIS2024-FMFI/serial-transformer#13]

**Comment by IvanaBekesova** [comment]
[datovy_model.docx](https://github.com/user-attachments/files/17708946/datovy_model.docx)

**Comment by pavelpetrovic** [comment]
[datovy_model_s_komentarmi.docx](https://github.com/user-attachments/files/17713750/datovy_model_s_komentarmi.docx)

**Comment by IvanaBekesova** [comment]
[datovy_model.docx](https://github.com/user-attachments/files/17807332/datovy_model.docx)

**Comment by pavelpetrovic** [comment]
tesim sa na spojeny dokument navrh
[datovy_model_edit.docx](https://github.com/user-attachments/files/17914831/datovy_model_edit.docx)
