### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2024-FMFI/serial-transformer#16]
Majú úlohu "akceptačných testov" - t.j. predtým, ako sa systém odovzdá zadávateľom na testovanie sa cez ne pre kontrolu musí prejsť. Niekoľko testovacích scenárov, kde každý scenár pozostáva z niekoľkých (napr. 10 bodov) v štýle 
3. AKCIA
   VÝSLEDOK
napríklad:
akcia: používateľ zmení konštantu zrýchlenia a stlačí [nastaviť]
výsledok: v rozhraní sa zmení label s aktuálne nastavenou rýchlosťou a teleskop sa začne pohybovať podľa novej konštanty

Jeden takýto scenár pokryje povedzme 30% katalógu požiadaviek, tak treba pridávať ďalšie scenáre, kým nebudú pokryté všetky.
Jeden človek tieto scenáre podľa KP pripraví a druhý skontroluje, že všetky požiadavky sú v nejakom scenári pokryté.

**Comment by Nemeth03** [comment]
[Testovacie scenáre.docx](https://github.com/user-attachments/files/17906136/Testovacie.scenare.docx)

**Comment by Nemeth03** [comment]
[Testovacie.scenare.docx](https://github.com/user-attachments/files/17984106/Testovacie.scenare.docx)
